# Statistics Using Python Part - I by Mohammad Wasiq

## Statistics
Statistics is the field of Science that deals with collection , analysis , interpretation or explanation and presentation of data . 
1. **Data Types**
<br> We can divide the data into two parts : 

**A. Categoricl Data / Qualitative Data :-** The objects being studied are grouped into categories based on some
qualitative characteristics. 

*The Categorical Data are further divided into two parts :* 
        
        a. Nominal Data : A type of categorical data in which objects fall into unordered categories. 
Ex -: *Gender :* Male , Female .
<br> *Education status :* Educated, Uneducated
<br> *Hair color :* Brown, Black, Blonde, Gray

        b. Ordinal Data : A type of categoical data in which order is important.
Ex -: *Class of degree :* 1st class, 2nd, 3rd class, fail
<br> *Level of happiness :* Very unhappy, Unhappy, OK, Happy, Very Happy
<br> *Degree of satisfaction :* Very Unsatisfied, Somewhat Unsatisfied, Neutral, Somewhat Satisfied, Very Satisfied 
    
**B. Non-Categorical Data / Quantitative Data :-** The objects being studied are ‘measured’ based on some quantitative trait. 
    
*Quantitative Data are also two types :* 
           
        a. Discrete Data : Data that can be counted.
Ex -: Number of students passing a stats exam
<br> Number of cars sold in a day.

        b. Continuous Data : Data which can be measured on scale but cann't be counted. 
Ex -: Weight, Height

Scale of Measurement for Continuous Data 

i. Interval Scale : Interval scales are numeric scales in which both the order and the exact differences between the values are considered. 
<br> For example, the difference between 60 and 50 degrees is a measurable 10 degrees, as is the difference between 80 and 70 degrees.

*Note :* Interval Scale data having no absolute zero. For example 0 degree doesn't mean no temperature.

ii. Ratio Scale : A ratio scale has all the properties of an interval scale. Ratio data on the ratio scale has measurable intervals.
<br> For example, the difference between a height of six feet and five feet is the same as the interval between two feet and three feet. 

*Note :* Where the ratio scale differs from the interval scale is that it also has a meaningful zero. 

2. **Organization of Data**

After the data have been collected, the main tasks a statistician must accomplish are the organization and presentation of the data. <br>
i. *Raw Data*: Data collected in original form (before it has been organized). <br>
ii. *Class*: A Quantitative or Qualitative category in which the raw data is placed. <br>
It must satisfy the following conditions : 
* There is usually between 5 and 20 classes.
* The classes must be mutually exclusive.
* The classes must be exhaustive. <br>
iii. *Frequency Distribution*: The frequency is the number of repetition of any value. <br>
A **frequency distribution** is the organization of raw data in tabular form, using classes and frequencies.<br>
Types of Frequency Distribution :<br>
a.Categorical b.Ungrouped c.Grouped

### Types of Statistics 
Statistics is mainly two types :
1. **Descriptive Statisrics** :- Descriptive Statistics provides us with tools (Tables, Graphs, Averages, Ranges, Correlations) for organizing and summarizing the inevi-table variability in collections of actual observations or scores .
2. **Inferential Statistics** :- The process of going from the known sample to the unknown population is called inferential statistical .

# Descriptive Statistics- I
Quantitative data in a mass exhibit certain general characteristics or they are differ from each other in  the following ways : 
### Descriptive Measures
1. **Measure of Central Tendency :** Measure of tendency is calles C.T. They show a tendency to concentrate at certain values,usually somewhere in the centre of the distribution. 

*Some Measures of Centeral Tendency :*

Measures of Location or Central Tendency or Measure of Location gives an idea about the central 
part of the distribution.

The main objective of Measure of Central Tendency are :
* To condense data in a single value.
* To facilitate comparison between data 

Requisites of a Good Measure of Central Tendency
<br> (i) It should be rigidly defined.
<br> (ii) It should be simple to understand and easy to calculate.
<br> (iii) It should be based upon all values of given data.
<br> (iv) It should be capable of further mathematical treatment.
<br> (v) It should have sampling stability.
<br> (vi) It should be not be unduly affected by extreme values.

---

* A. **Mean / Arithmetic Mean**  

* *Discrete Case :* Arithmetic Mean (A.M.) of a set of observations is their sum divided by the number of observations
<br> Let $x_1, x_2, \dots x_n$ are observations, then
$$\bar{x} = \frac{1}{n} \sum_{i=1}^n x_i$$

* *Discrete or ungrouped frequency distribution :* In case of frequency distribution $X_i | f_i \,\, i=1,2,...,n$, where $f_i$ is the frequency of the variable $x_i$, then
$$\bar{x} = \frac{1}{N} \sum_{i=1}^n f_ix_i$$
where, $N = \sum_{i=1}^n f_i$

* *Grouped or continuous frequency distribution :* In case of grouped or continuous frequency distribution, is taken as the midpoint of the corresponding class.
$$\bar{x} = \frac{1}{N} \sum_{i=1}^n f_ix_i$$
where, $N = \sum_{i=1}^n f_i$

**Properties of Arithmetic Mean :**
1. Arithmetic mean is dependent of change of origin and scale.
2. Algebraic sum of the deviation of a set of values from their arithmetic mean is always zero.
3.  The sum of the square of the deviation of a set of values is minimum when taken about mean
4. **Weighted Average or Weighted Mean :** A method of computing a kind of arithmetic mean of a set of numbers in which some elements of the  set carry more importance (weight) than others.
<br> Let there be $n$ observations $x_1,x_2,...,x_n$ and $w_1,w_2,...,w_n$ are their respective weights in the set. 
<br> Then weighted mean is calculated using the formula
$$\bar{x_w} = \frac{\sum_{i=1}^n w_ix_i}{\sum_{i=1}^n w_i}$$
5. **Trimmed Mean :** A trimmed mean computed by "trimming away" a certain percent of both the largest and the smallest set of values. For example, the $t\%$ trimmed mean is found by eliminating the largest $t\%$ and smallest $t\%$ and computing the average of the remaining values. It is denoted by $\tilde{x}$.

*Note :* The trimmed mean is, in general, more insensitive to outliers (extreme values) than the sample mean. 

*Merits of Arithmetic Mean :*
1. It is rigidly defined.
2. It is easy to understand and easy to calculate.
3. It is based upon all values of the given data.
4. It is capable of further mathematical treatment.
5. It is not much affected by sampling fluctuations.

*Demerits of Arithmetic Mean :*
1. It cannot be calculated if any observation is missing.
2. It cannot be calculated for the data with open-end classes.
3. It is affected by extreme values.
4. It cannot be located graphically.
5. It may be number which is not present in the data.
6. It cannot be calculated for the data representing qualitative characteristic.

---

* **B. Median**

Median of a distribution is the value of the variable which divides it into two equal parts, that is the value such that the number of observations above it is equal to the number of observations below it. 
<br> The median is a positional average.

*Application :*
<br> Median is only average to be used while dealing with qualitative data which cannot be measured quantitatively but can be arranged in ascending or descending order of magnitude. 

* *Discrete data :* Arrange all the observations in ascending or descending order.
* If the number of observations are **odd**, then
$$Median = \Bigg(\frac{n+1}{2} \Bigg)^{th} \,\, observation = \frac{x_n+1}{2}$$

* *Discrete frequency distribution :*

Steps for calculating median
* Find $N/2$, where $n=\sum_{i=1}^n f_i$
* Locate cumulative frequency (c.f.) just greater than $N/2$
* The value of $x$ corresponding to that c.f. is the median 


* *Continuous frequency distribution (grouped data)*

Steps for calculating median
* Find $N/2$, where $n=\sum_{i=1}^n f_i$
* Locate cumulative frequency (c.f.) just greater than $N/2$
* The class corresponding to that c.f. is the median class
* Then use following formula to calculate median
$$Median = l_m + \frac{h_m}{f_m} \Big(\frac{N}{2}-C_p\Big)$$
where, $l_m :$ lower limit of the median class
<br> $f_m :$ frequency of the median class
<br> $h :$ class width
<br> $C_p :$ c.f of the class preceeding to the median class

*Merits :*
1. It is rigidly defined.
2. It is easy to calculate and understand
3. It can be located merely by inspection.
4. It is not all affected by extreme values.
5. It can be calculated for the distributions with open-end classes.

*Demerits :*
1. In case of even number of observations median cannot be determined exactly.
2. It is not based on all observations.
3. It is not suitable for algebraic treatment.
4. As compared to mean, it is affected much by fluctuations of sampling. 

---

* **C. Mode :** Mode is the value which occurs most frequently in a set of observations.

* *Discrete frequency distribution*

In case of discrete frequency distribution, mode is the value, which corresponds to maximum frequency

**Note :** In any one or more of the following cases
* If the maximum frequency is repeated.
* If the maximum frequency occurs in the very beginning or at the end of the distribution.
* If there are irregularities in the distribution.

* *Continuous frequency distribution (Grouped data)*

* Identify the modal class corresponding to the maximum frequency.
* Calculate the mode using the following formula
$$Mode = l + \frac{f_m-f_p}{2\, f_m-f_p-f_s} \times h$$
where, 
* $l :$ Lower limit of the modal class
* $h :$ Class width
* $f_m :$ Frequency of the modal class
* $f_p :$ Frequency of the preceeding class 
* $f_s :$ Frequency of the successive class

**Remarks :**
1. In any one or more of the cases as defined for discrete case modal class is determined by the method of grouping.
2. If the method of grouping gives the modal class which does not correspond to the maximum frequency or in some cases $2\, f_m-f_p-f_s=0$, in such cases mode is obtained by using formula
$$Mode = l + \frac{h(f_m-f_p)}{|2\, f_m-f_p| + |f_m-f_s|}$$

*Merits :*
1. It is easy to understand and easy to calculate.
2. It is not affected by extreme values or sampling fluctuations.
3. It can be located just by inspection in many cases.
4. It is always present within data.
5. It is applicable for both quantitative and qualitative data.

*Demerits :*
1. It is not rigidly defined.
2. It is not based upon all values of the given data.
3. It is not capable of further mathematical treatment.

**Relationship Between Mean, Median and Mode**
1. In positively skewed distribution, the presence of exceptionally high values affect mean more than median and mode. Therefore
$$Mean>Median>Mode$$
2. In negatively skewed distribution, the presence of exceptionally low values depress the mean most, followed by median and mode. Thus
$$Mean<Median<Mode$$

In the above two situation, it can be observed that median always lies between mean and mode. 
<br> Thus, if the number of observations in any set of data is large enough to yield a fairly smooth and moderately skewed distribution, the mean, median and mode are empirically related as 
$$Mode = 3(Median) - 2(Mean)$$
3. In the case of symmetrical distribution, the mean, median and mode coincide. That is
$$Mean = Median = Mode$$

---

* **D. Geometrical Mean :** Geometric Mean (GM) of a set of observations is the $n^{th}$ root of their product.

* *Discrete data*

Let $x_1, x_2,...,x_n$ are $n$ observations, then
$$GM = n_{\sqrt{x_1 \times x_2\times...\times x_n}}$$

or
$$GM= Antilog\Big(\frac{1}{n} \sum_{i=1}^n log\,x_i \Big)$$

* *Discrete frequency distribution*

In case of frequency distribution $x_i|f_i ;\, i=1,2,...,n$ where $f_i$ is the frequency of the variable $x_i$, the geometric mean is calculated by using formula
$$GM = n_{\sqrt{x_1^{f_1} \times x_2^{f_2} \times...\times x_n^{f_n}}}$$
or
$$GM= Antilog\Big(\frac{1}{N} \sum_{i=1}^n f_i log\,x_i \Big)$$
where $N=\sum_{i=1}^n f_i$ 

**Uses :**
1. To find rate of population growth and rate of interest.
2. In construction of index number.

---

* **E. Harmonic Mean :** Harmonic mean of the given observations is defined as the reciprocal of the arithmetic mean of the reciprocals of the given set of observations.

If $x_1, x_2,...,x_n$ are $n$ observations, with their reciprocals $\frac{1}{x_1}, \frac{1}{x_2},....,\frac{1}{x_n}$, then the Harmonic Mean(HM) is given by 
$$HM = \frac{1}{\frac{1}{n}\Big(\frac{1}{x_1}, \frac{1}{x_2},....,\frac{1}{x_n} \Big)}= \frac{n}{\sum_{i=1}^n\frac{1}{x_i}}$$

In this case of ungrouped frequency distribution
$$HM = \frac{1}{\frac{1}{N}\Big(\frac{f_1}{x_1}, \frac{f_2}{x_2},....,\frac{f_n}{x_n} \Big)}= \frac{n}{\sum_{i=1}^n\frac{f_i}{x_i}}$$
where, $N=\sum_{i=1}^n f_i$

In the case of grouped frequency distribution $x_i, \,\, i=1,2,...,n$ are the mid points of the class intervals.

**Note :** For computation of weighted harmonic mean $f_i$ is replaced with the weight of $i^{th}$ observation $w_i$.

**Uses**
* The Harmonic mean is often used to calculate the average of the ratios or rates. It is the most appropriate measure for ratios and rates because it equalizes the weights of each data point. For instance, the arithmetic mean places a high weight to large data points, while geometric mean gives a lower weight to the smaller data points.
* It is most appropriate average where unit of observation (such as per day, per hour, per unit, per worker etc.) remains the same and act being performed, such as covering distance.

**Relationship between AM, GM and HM**

If we compute these three averages for the same data set, then we get the relation
$$AM>GM>HM$$ 
provided that the observations comprising a set of data are not same.

If the set of data has the same observations, then
$$AM=GM=HM$$
---

**Some Partition Values :**
* **i. Quartiles :** Three points that divide the whole distribution into four equal parts are called quartiles.

* *Discrete Data*

* $1^{th}$ $Quartile$ $Q_1$ is the value such that $25\%$ of the ranked data are smaller and $75\%$ are larger.
$$
Q_1 = \begin{cases} 
  \frac{X_{n+1}}{4},  & \text{when n is odd} \\
  \frac{1}{2} \Big(X_{\frac{n}{4}} + X_{\frac{n}{4}+1} \Big)  & \text{when n is even}
\end{cases}
$$

* $2^{th}$ $Quartile$ $Q_2$ is the **Median**.

* $3^{th}$ $Quartile$ $Q_3$ is the value such that $75\%$ of the ranked data are smaller and $25\%$ are larger.
$$
Q_3 = \begin{cases} 
  \frac{X_{3(n+1)}}{4},  & \text{when n is odd} \\
  \frac{1}{2} \Big(X_{\frac{3n}{4}} + X_{\frac{3n}{4}+1} \Big),  & \text{when n is even}
\end{cases}
$$

* *Discrete Frequency Distribution*

Steps for calculating quartiles
* Find $\frac{jN}{4};\,\, j=1,2,3$ where $N=\sum_{i=1}^n f_i$ 
* See cumulative frequency(c.f.) just greater than $\frac{jN}{4}$
* The value of corresponding to that c.f. is the $Q_j,\,\, j=1,2,3$

* *Continuous Frequency Distribution (Grouped Data)*
$$Q_j = l_q + \frac{h}{f_q} \Big(\frac{jN}{4}-C_p\Big),\,\, j=1,2,3$$
where, $l_q :$ Lower limit of the that quartile class
<br> $f_q :$ Frequency of the that quartile class
<br> $h :$ Class width
<br> $C_p :$ c.f. of the class preceeding to the quartile class.

---

* **ii. Deciles :** Nine points that divide the whole distribution into ten equal parts are called deciles.

* *Discrete Data*

Steps for calculating deciles
* Find $\frac{kN}{10};\,\, k=1,2,...,9$ where $N=\sum_{i=1}^n f_i$ 
* See cumulative frequency(c.f.) just greater than $\frac{kN}{10}$
* The value of corresponding to that c.f. is the $D_k,\,\, k=1,2,...,9$

* $5^{th}$ $Decile$ $D_5$ is the **Median**.

* *Continuous Frequency Distribution (Grouped Data)*
$$D_k = l_d + \frac{h}{f_d} \Big(\frac{kN}{10}-C_p\Big),\,\, k=1,2,...,9$$
where, $l_d :$ Lower limit of the that decile class
<br> $f_d :$ Frequency of the that decile class
<br> $h :$ Class width
<br> $C_p :$ c.f. of the class preceeding to the decile class.

---

* **ii. Percentiles :** Ninety-nine points that divide the whole distribution into 100 equal parts are called percentile.

* *Discrete Data*

Steps for calculating deciles
* Find $\frac{lN}{100};\,\, l=1,2,...,99$ where $N=\sum_{i=1}^n f_i$ 
* See cumulative frequency(c.f.) just greater than $\frac{lN}{100}$
* The value of corresponding to that c.f. is the $P_l,\,\, l=1,2,...,99$

* $50^{th}$ $Percentile$ $P_50$ is the **Median**.

* *Continuous Frequency Distribution (Grouped Data)*
$$P_l = l_p + \frac{h}{f_p} \Big(\frac{lN}{100}-C_p\Big),\,\, l=1,2,...,99$$
where, $l_p :$ Lower limit of the that percentile class
<br> $f_p :$ Frequency of the that percentile class
<br> $h :$ Class width
<br> $C_p :$ c.f. of the class preceeding to the percentile class.

----

2. **Measures of Variation or Dispersion :** The data vary about a measure of centeral tendency and these measures of deviation are called measures of variation or dispersion. 

**Characteristic for ideal measure of dispersion :**
* (i) It should be rigidly defined.
* (ii) It should be simple to understand and easy to calculate.
* (iii) It should be based upon all values of given data.
* (iv) It should be capable of further mathematical treatment.
* (v) It should have sampling stability.

**Some Measure of Dispersion :**
* **A. Range :** The range is the *difference between the largest and smallest values* of the distribution.
<br> Let $x_1, x_2,...,x_n$ are the set of $n$ abservations, then 
$$Range = max(x_1, x_2,...,x_n)-min(x_1, x_2,...,x_n)$$
* One of the simplest measures of variability to calculate. 
* Depends only on extreme values and provides no information about how the remaining data is distributed. 

---

* **B. Quartile Deviation :** Quartile Deviation or Semi Inter Quartile Range $Q$ is given by
$$Q= \frac{1}{2}(Q_3-Q_1)$$
where $Q_1$ and $Q_3$ are the first and third quartiles of the distribution.

---

* **C. Mean Deviation :** 

* *Discrete Data*

Let $x_1,x_2,...,x_n$ are $n$ observations, then 
$$MD = \frac{1}{n}\sum_{i=1}^n|x_i-A|$$
where $A$ is generally taken as *mean, median* and *mode*.

* *Discrete Frequency Distribution*

In case of frequency distribution $x_i|f_i; \,i=1,2,...,n$, where $f_i$ is the frequency of the variables $x_i$, then 
$$MD = \frac{1}{n}\sum_{i=1}^n f_i|x_i-A|$$
where $N=\sum_{i=1}^nf_i$

---

* **D. Variance :** Variance is a measure of how data points differ from the mean.

* *Discrete Case*

Let $x_1,x_2,...,x_n$ are observations, then Standard Deviation generally denoted by is given by
$$\sigma^2= \frac{1}{n} \sum_{i=1}^n(x_i -\bar{x})^2$$

* *Discrete Frequency Distribution*

In case of frequency distribution $x_i|f_i; \,i=1,2,...,n$, where $f_i$ is the frequency of the variables $x_i$, then 
$$\sigma^2= \frac{1}{n} \sum_{i=1}^n f_i(x_i -\bar{x})^2$$

* It is based on all the observations; it is better measure of dispersion than mean deviation.
* The artificiality created in the case of mean deviation is removed by squaring the .
* It is capable of further mathematical treatment

---

**Sample Variance :**

Let $x_1,x_2,...,x_n$ are observations taken from a population and sample size is small, then we replace the denominator $n$ by $(n-1)$ in formula of standard deviation and variance.

Therefore the Sample Standard Deviation generally denoted by is given by
$$s^2= \frac{1}{n-1} \sum_{i=1}^n(x_i -\bar{x})^2$$
But when sample size is large, then no need to do this modification as $\frac{n}{n-1}\rightarrow as\,\, n \rightarrow \infty$


* **E. Standard Deviation / Root Mean Square Deviation :** It is the square root of *variance*.
$$SD= \sqrt{\sigma^2}= \sigma$$

**Note :* Standard deviation and Variance are independent of change in origin but not the scale.

---

**Some Useful Results :**

Let $x$ is any variable and $k$ be any constant. If we denote Mean by $M$ and Variance by $V$, then 

**Mean :**
1. $M(k)=k$
2. $M(x\mp k) = M(x) \mp k$
3. $m(kx)=k \times M(x)$
4. $M(kx \mp c)= k \times M(x) \mp c$

where $c$ is any other constant.

**Variance :**
1. $V(k)= 0$
2. $V(x\mp k)= V(x)$
3. $V(kx)=k^2 \times V(x)$
4. $SD(kx)=k \times SD(x)$

---

**Coefficient of Disperion :**

Sometimes we want to compare the variability of two series which differ widely in their averages or which are measured in different units, we do not only calculate the measure of dispersion but we calculate coefficient of dispersion, which are pure numbers independent of unit of measurement.

The Coefficient of Dispersion (C.D.) based on different measure of dispersion are as below:

1. **CD based upon Range :** $\frac{A-B}{A+B}$

where $A$ is the largest value and $B$ is the smallest value in the series.

2. **CD based upon Quartile Deviation :** $\frac{Q_3-Q_1}{Q_3+Q_1}$

where $Q_1$ and $Q_3$ are first and third quartiles respectively.

3. **CD based upon Mean Deviation :** $\frac{M.D.}{\bar{x}}$

4. **CD based upon SD :** $\frac{\sigma}{\bar{x}}$

5. **Coefficient of Variation / C.V. :** 100 times the coefficient of dispersion based on standard deviation (S.D.) is called Coefficient of Variation, that is $\frac{\sigma}{\bar{x}} \times 100$

---

3. **Measures of Skewness :** The data in a frequency distribution may fall into symmetrical o asymmertical patterns. The measures of direction and degree of symmetry are called measure of skewness.

Skewness Means :Lack of Symmetry

*Some Measure of Skewness*
1. $S_k=M-M_d$
2. $S_k=M-M_0$
3. $Q_1+Q_3-2Q_2 \quad | \quad Q_1+Q_3-2M_d$
4. $\frac{M-M_0}{\sigma}$
5. $\frac{3(M-M_0)}{\sigma}$

I.*Prof. Karl Pearson's Coefficient of Skewness* : $\frac{(M-M_0)}{\sigma}, \,\, limit\,\, of\,\, S_k \pm3$

II.*Prof. Bowley's Coefficient of Skewness* : $\frac{(Q_1+Q_3-2Q_2)}{Q_3-Q_1}$

III.*Based upon Moments,coefficient of skewness* : $S_k=\frac{\sqrt{\beta_1}(\beta_2+3)}{2(5\beta_2-6\beta_1-9)}$

---

4. **Measure of Kurtosis :** Polygons of frequency distributions exhibit flatness or peakedness of the frequency curves. The measures of peakedness or flatness of the frequency curves are called measures of kurtosis.
$$\beta_1=\frac{\mu_{2}^3}{\mu_{3}^2} \quad , \gamma_1= {\sqrt{\beta_1}}$$

$$\beta_2=\frac{\mu_4}{\mu_{2}^2} \quad , \gamma_1= \beta_1-3$$

* If $\beta_2<3,\quad \Rightarrow \gamma_2<3$  Curve is $Platykurtic$
* If $\beta_2=3,\quad \Rightarrow \gamma_2=3$  Curve is $Mesokurtic/Normal$
* If $\beta_2>3,\quad \Rightarrow \gamma_2>3$  Curve is $Leptokurtic$

---

In [1]:
# Import the Statistics Librarry
import statistics as stat

In [2]:
# Creating a Vector
x = [60,83,83,91,100] 

In [3]:
# To Calculate mean of x
stat.mean(x) 

83.4

In [4]:
# To Calculate mean of x
stat.mean(x) 

83.4

In [5]:
# To calculate mode of x
stat.mode(x)

83

In [7]:
# To calculate standard deviation of x
stat.stdev(x) 

14.842506526863986

In [8]:
# To calculate vaiance of x
stat.variance(x) 

220.3

In [10]:
import math as m
m.sqrt(stat.variance(x))

14.842506526863986

In [11]:
# To calculate quartile of x
stat.quantiles(x) 

[71.5, 83.0, 95.5]

In [12]:
# To Calculate the minimum value of x
min(x) 

60

In [13]:
# to Calculate the maximum value of x
max(x)

100

In [14]:
# To calculate geometric mean of x
stat.geometric_mean(x) 

82.23747464222964

In [15]:
# To calculate harmonic mean of x
stat.harmonic_mean(x)

80.9689545753409

In [16]:
# To Calculate the Coefficient of dispersion based on Range
cdr=(max(x)-min(x))/(max(x)+min(x))
cdr

0.25

In [17]:
# To Calculate the Coefficient of dispersion based on Quartile
cdq = (99.5-71.5)/(99.5+71.5)
cdq

0.16374269005847952

In [20]:
# To Calculate the Coefficient of dispersion based on Standard Deviation
cdsd = stat.stdev(x)/stat.mean(x)
cdsd

0.1779677041590406

In [21]:
# To Calculate the Coefficient of Variation
cv = cdsd*100 ; cv

17.79677041590406

In [22]:
# To Calculate the Measure of Skewness
from scipy.stats import skew
sk = skew(x)  ; sk

-0.6667369269731003

In [24]:
# To Calculate the Skewness by Median
sk1 = stat.mean(x)-stat.median(x) ; sk1

0.4000000000000057

In [25]:
# To Calculate the Skewness by Mode
sk2 = stat.mean(x)-stat.mode(x) ; sk2

0.4000000000000057

In [26]:
# To Calculate the Skewness by Quartile
sk3 = (71.5+95.5-2*83.0) ; sk3

1.0

In [27]:
# Skewness by mode and sd
sk4 = (stat.mean(x)-stat.mode(x))/(stat.stdev(x))
sk4

0.026949626013371215

In [28]:
# To Calculate the Skewness by median and sd
# Prof. Karl Pearson's Coefficient of Skewness 

sk5 = 3*(stat.mean(x)-stat.median(x))/(stat.stdev(x))
sk5

0.08084887804011363

In [29]:
# To Calculate the Skewness
# Prof. Bowley's Coefficient of Skewness 

sk6 = (71.5+95.5-2*83.0)/(95.5-71.5)
sk6

0.041666666666666664

In [30]:
# To Calculate the Measure of Kurtosis
from scipy.stats import kurtosis 
kts = kurtosis(x)  ; kts # This graph is platykurtic

-0.5590149733918302

## Correlation
1. **Simple Correlation :-**
Correlation measures how variables are related. 

The correlation coefficient is used to quantify the strength and the direction of the linear relationship between two variables and usually denoted by r . The linear correlation coefficient is sometimes referred to as the *Pearson product moment correlation coefficient* in honour of its developer Professor Karl Pearson.

Pearson’s correlation coefficient, used when
* a. Data is quantitative.
* b. Distribution of variables is normal.
* c. Linear relationship between two variables.
* d. All observations should be independent .
$$r = (\rho) = \frac{Cov(X,Y)}{\sigma_X \sigma_Y},\quad -1< \rho < +1$$
where, $Cov(X,Y)=\frac{\sum_{i\neq j=1}^n (X_i-\bar{X})(Y_j-\bar{Y})}{n}$

**Remarks :**
<br> The value of $r$ is such that $-1 \le r \le +1$.The *+* and *-* signs are used positive linear correlations and negative correlations, respectively. <br>
* i. **Positive Correlation :** If  two variables X and Y deviate in same direction, that is the increase/decrease in one results in corresponding increase/decrease in other, the correlation is said to be positive. *For example height and weight of group of persons.*
* ii. **Negative Correlation :** If two variables X and Y deviate in opposite direction, that is the increase/decrease in one results in corresponding decrease/increase in other, the correlation is said to be negative. *For example pressure and volume of gas*.
* iii. **No Correlation :** The two variables X and Y is said to be uncorrelated if and increase/decrease in one results in no change in other. *For example weight and IQ.*
* iv. **Perfect Correlation :** The correlation is said to be perfect if the deviation in one variable followed by the corresponding proportional deviation in other. The value $r=+1$ indicates perfect positive correlation whereas $r=-1$ means perfect negative correlation.

The correlation coefficient r is a dimensionless quantity; that means it does not depend on
the units employed .

**Note that :**
* If r = 0 this means no association or correlation between the two variables.
* If $0 <r< 0.25 | -0.25 <r< 0$ : weak **positive | negative correlation.**
* If $0.25 <r< 0.75 | -0.75 <r< -0.25$: intermediate **positive | negative correlation.**
* If $0.75 <r< 1 | -1 <r< -0.75$: strong **positive | negative correlation.**
* If $r=+1 | r=-1$: perfect **positive/negative correlation.**

**Spearman's rank correlation coefficient :**

Spearman's rank correlation coefficient, named after Charles Spearman, is a non-parametric measure of correlation. Unlike the Pearson product-moment correlation coefficient, it does not require the assumption that the relationship between the variables is linear, nor does it require the variables to be measured on interval scales; it can be used for variables measured at the ordinal level.
$$r_{s}=1-\frac{6\sum_{i=1}^n d_{i}^2}{n(n^2-1)}$$ 
where $n =$ no. of obs. in each series.

---

2. **Partial Correlation :**

Partial correlation analysis involves studying the linear relationship between two variables after excluding the effect of one or more independent factors. 
<br>For example suppose that there are three variables Sale$(X_1)$,Price$(X_2)$ and Production $(X_3)$ and one wants to find the linear relationship between Sale$(X_1)$ ,Price$(X_2)$ after controlling the Production$(X_3)$ .

**coefficient of Partial Correlation :-** Partial correlation between $X_1$ and $X_2$ after controlling the effect of $X_3$ and usually denoted by $r_{12.3}$ is given as :
$$r_{12.3}=\frac{r_{12}-r_{13}r_{23}}{\sqrt{(1-r_{13}^2)(1-r_{23}^2)}}$$

Similarly , 
$$r_{13.2}=\frac{r_{13}-r_{12}r_{23}}{\sqrt{(1-r_{12}^2)(1-r_{23}^2)}}$ , as $r_{23}=r_{32}$$

and
$$r_{23.1}=\frac{r_{23}-r_{12}r_{13}}{\sqrt{(1-r_{12}^2)(1-r_{13}^2)}}$$

----

3. **Multiple Correlation :** 
Sometimes we find interrelationship between many variables and value of one variable may be influenced by many others. 
<br>For example the yield of crop per hectare, say $(X_1)$ depends upon quality of seed$(X_2)$,fertility of soil $(X_3)$,fertilizer used$(X_4)$, irrigation facilities$(X_5)$, weather condition$(X_6)$ and so on. When someone is interested in studying joint effect of variables upon a variable not included in that group, our study is that of multiple correlation and multiple linear regression analysis.

**Coefficient of Multiple Correlations :** Consider a trivariate distribution in which each of the variable $X_1,X_2,and X_3$ has $n$ observations.

The  multiple correlation coefficient of $X_1, X_2, \,\,and\,\, X_3$ , usually denoted by $R_{1.23}$ is given by :
$$R_{1.23}^2=\frac{r_{12}^2+r_{13}^2-2*r_{12}r_{13}r_{23}}{1-r_{23}^2}$$
This is also called simple correlation between $X_1$ and joint effect of $X_2$ and $X_3$ on $X_1$.

The multiple correlation coefficient of $X_2$ and $X_1$ on $X_3$ is given as :
$$R_{2.13}^2=\frac{r_{12}^2+r_{23}^2-2*r_{12}r_{13}r_{23}}{1-r_{13}^2}$$

and the multiple correlation coefficient of $X_3$ and $X_1$ on $X_2$ is
$$R_{3.12}^2=\frac{r_{13}^2+r_{23}^2-2*r_{12}r_{13}r_{23}}{1-r_{12}^2}$$

$r_{ij}=r_{ji,i\neq j}$ is the correlation between $X_i$ and $X_j$ .
<br> **To see the correlation between variables by graphs , we use _Scatter plot_ and _Line chart_**

---

In [31]:
# To Calculate the Correlation between two variables 
x1 = [4,3,5,6,7,7,8,9,3,5]
x2 = [5,3,5,6,7,8,4,3,6,8]
import pingouin as pg
pg.corr(x1,x2)

n      r         CI95%     r2  adj_r2    p-val   BF10  power
pearson  10 -0.044  [-0.66, 0.6]  0.002  -0.283  0.90393  0.389  0.051

In [33]:
# To Calculate the correlation coefficient 
np.corrcoef(x1, x2)

array([[ 1.        , -0.04400265],
       [-0.04400265,  1.        ]])

In [32]:
# To Calculate the  Karl Pearson's Correlation 
from scipy.stats import pearsonr
kpc = pearsonr(x1, x2)
kpc

(-0.04400265197307414, 0.903930356086283)

In [34]:
# To Calculate the Spearman's rank correlation coefficient
from scipy.stats import spearmanr
srcc = spearmanr(x1, x2)
srcc

SpearmanrResult(correlation=-0.021671930489041497, pvalue=0.9526149117123045)

In [36]:
#  To Calculate the Partial Correlation 
# data: name of the dataframe
# x, y: names of columns in the dataframe
# covar: the name of the covariate column in the

import pandas as pd
df = pd.DataFrame({'CurrentGrade':  [82, 88, 75, 74, 93, 97, 83, 90, 90, 80],
        'Hours': [4, 3, 6, 5, 4, 5, 8, 7, 4, 6],
        'ExamScore': [88, 85, 76, 70, 92, 94, 89, 85, 90, 93]})
df

# find partial correlation between 
# hours and exam score while controlling for grade
pg.partial_corr(df, x='Hours' ,
                y='ExamScore', covar= 'CurrentGrade')

n      r         CI95%     r2  adj_r2     p-val   BF10  power
pearson  10  0.191  [-0.5, 0.73]  0.036  -0.239  0.597831  0.438  0.082

In [37]:
# To Calculate the all pairwise partial correlations, rounded to three decimal places
df.pcorr().round(3)

CurrentGrade  Hours  ExamScore
CurrentGrade         1.000 -0.311      0.736
Hours               -0.311  1.000      0.191
ExamScore            0.736  0.191      1.000

In [38]:
# To Calculate the five number theory
df.describe()

CurrentGrade      Hours  ExamScore
count     10.000000  10.000000  10.000000
mean      85.200000   5.200000  86.200000
std        7.641989   1.549193   7.714345
min       74.000000   3.000000  70.000000
25%       80.500000   4.000000  85.000000
50%       85.500000   5.000000  88.500000
75%       90.000000   6.000000  91.500000
max       97.000000   8.000000  94.000000

### Covariance
covariance is a measure of the relationship between two random variables. The metric evaluates how much – to what extent – the variables change together. In other words,it is essentially a measure of the variance between two variables. However, the metric does not assess the dependency between variables.

Unlike the correlation coefficient, covariance is measured in units. The units are computed by multiplying the units of the two variables. The variance can take any positive or negative values. The values are interpreted as follows:
* i. **Positive Covariance :-** Positive Covaiance indicates that two variables tend to move in same direction .
* ii. **Negative Covariance :-** Negative Covariance revels that two variables tends to move in inverse direction.
$$Cov(X,Y) = \frac{\sum_{i\neq j=1}^n (X_i-\bar{X})(Y_j-\bar{Y})}{n}$$

__Difference between Covariance and Correlation__ 
<br>Covariance and correlation both primarily assess the relationship between variables. The closest analogy to the relationship between them is the relationship between the variance and standard deviation.

**Covariance** measures the total variation of two random variables from their expected values. Using covariance, we can only gauge the direction of the relationship (whether the variables tend to move in tandem or show an inverse relationship). However, it does not indicate the strength of the relationship, nor the dependency between the variables.
<br>On the other hand, **Correlation** measures the strength of the relationship between variables. Correlation is the scaled measure of covariance. It is dimensionless. In other words, the correlation coefficient is always a pure value and not measured in any units.

$Correlation = (\rho)=\frac{Cov(X,Y)}{\sigma_X \sigma_Y},\quad -1< \rho < +1$

In [39]:
# To Calculate the Covariance
from numpy import cov
cov = cov(df['CurrentGrade'],df['ExamScore'])
cov

array([[58.4       , 42.73333333],
       [42.73333333, 59.51111111]])

<center><h1> Thank You </h1></center>

## Discrete Probability Distribution
### Binomial Distribution 
If we repeat Bernoulli tial n times and let _x_ be the  the number of successes in n trials and each trial has constant probability of success (p). Then the probability distribution of number of successes (X) is called Binomial distribution.

In the definition above, we notice that the following conditions need to be satisfied for a binomial experiment : 
* i. There are a fixed number of n trials carried out.
* ii.The outcome of a given trial is either a “success” or “failure”.
* iii.The probability of success (p) remains constant from trial to trial.
* iv.The trials are independent, and the outcome of a trial is not affected by the outcome of any other trial.

We denote the Binomial Distribution as:
$X \sim B(x,n,p)$

The PMF or Probability Distribution is given by-
$$P(X=x)={n \choose x}p^{x}(1-p)^{n-x} ;\quad x=0,1,2 \cdots n ; q=(1-p)$$

Binomial Distribution has :
* mean $\mu=np$ 
* variance $\sigma^2=np(1-p)$ 
* mgf is $M_{x}(t)=((1-p)+pe^t)^n$

Recursive Relation for Probability :
$$P(X=x+1)=\frac{p}{q}\frac{(n-x)}{x+1}P(X=x)$$
* For *small p* and *large n*, the binomial distribution *skewed right*.
* For *p=0.5* and *small n*, the binomial distribution *symmetry*.
* For *large p* and *small n*, the binomial distribution *skewed left*.

* 10 binomial Random Sample of n=10 , prob.=0.6

In [40]:
[n,p,size] = [10,0.6,10]
rbinom = np.random.binomial(n,p,size) ;rbinom

array([6, 7, 3, 4, 9, 4, 6, 6, 4, 7])

* Ten 10 trials for coin toss generate 10 data points

In [41]:
from numpy import random as r
b1 = r.binomial(n=10,p=0.5) ; b1

3

* Simulate the 10 random no. with prob.=0.5

In [42]:
b11 = r.binomial(n=10,p=0.5,size=10) ; b11

array([2, 1, 7, 4, 2, 3, 6, 6, 7, 8])

In [43]:
# Mean of binomial n=10,p=0.5
np.mean(b11)

4.6

In [44]:
# SD of b11
np.std(b11)

2.3748684174075834

**PMF of Binomial Distribution**
* The chance of 3 sixes in 10 rolls of a die . Find its prob.

`stat.binom(x=3, n=10, p=1/6)`

In [45]:
from scipy import stats 
bpmf = stats.binom.pmf(3, 10, 1/6) ; bpmf

0.15504535957425197

In [46]:
# To calculate the P(2<=X<=4)=P(X=2)+P(X=3)+P(X=4)
p24 = stats.binom.pmf([2,3,4], 10, 1/6) ;p24

array([0.29071005, 0.15504536, 0.05426588])

In [47]:
sum(p24)

0.5000212846269625

In [48]:
# To calculate the P(X>3)=1-P(X<=3)
p3 = 1-sum(stats.binom.pmf([1,2,3], 10, 1/6)) ;p3
round(p3,3)

0.231

In [49]:
# Random Number Generation
br = stats.binom.rvs(n=10,p=0.5,size=10) ; br

array([5, 5, 7, 4, 5, 8, 4, 6, 9, 5])

In [50]:
# CDF of binomial distribution
bcdf = stats.binom.cdf(3,10,0.5) ; bcdf

0.17187499999999994

### Poisson Distribution
The Poisson distribution is used to model the number of events occurring within a given time interval.

Poisson distribution occurs when there are events which do not occur as outcomes of a definite number of trials (unlike that in binomial) of an experiment but occur at random points of time and space, wherein our interest lies only in the number of occurrences of the event, not its non-occurrences.

Here are some situations where we can use Poisson distribution
* i. Number of WhatsApp messages received on a cell phone in some unit of time.
* ii. Number of calls received on your mobile in some unit of time.
* iii. Number of aircraft accidents in some unit of time.
* iv. Number of items failed in manufacturing process during given time period
* v. Number of defective items in a box of 100 items.

*We denote Poisson Distribution as :*

$X \sim P(\lambda)$
<br>The PMF of Poisson Distribution is written as :
$$P(X=x)=\frac{e^{\lambda}\lambda^{x}}{x!} , \quad x=0,1,2,3,\cdots,\infty$$
Poisson Distribution has : 
* same mean and vaiance i.e. $\lambda=np$ 
* mgf $M_{x}(t)=e^{\lambda(e^{t}-1)}$

Recurrence relation for probability:
$$P(X=x+1)=\frac{\lambda}{(x+1)}P(X=x)$$
If in the pmf of Binomial Distribution $n\rightarrow \infty \quad and \quad p\rightarrow 0$ then it's convert into Poisson Distribution . 

In [51]:
from numpy import random as r
from scipy import stats
import statistics as stat

* 10 Poisson Random Sample of mean=3

In [52]:
[mean,size] = [3, 10]
rpois = np.random.poisson(mean,size) ;rpois

array([4, 2, 1, 3, 2, 1, 3, 1, 5, 0])

In [53]:
# Generate a random 1x10 distribution for occurence 2:
p = r.poisson(lam=2, size=10) ;p

array([1, 3, 4, 4, 2, 1, 1, 4, 0, 1])

In [54]:
# Generate random values from Poisson distribution 
# with mean=3 and sample size=10
p1 = stats.poisson.rvs(mu=3, size=10) ;p1

array([2, 2, 1, 3, 3, 8, 2, 0, 3, 2])

If X be the number of calls received at your cell phone with mean number of calls 

2. Find the probability that on a randomly selected occasion there will be 
* i) None 
* ii) One
* iii) Atleast one 
* iv) Atmost one

In [55]:
# (i) None = P(X=0)
pi = stats.poisson.pmf(0, 2) ;pi

0.1353352832366127

In [56]:
# (ii) One = P(X=1)
pii = stats.poisson.pmf(1, 2) ; pii

0.2706705664732254

In [57]:
# (iii) At least one=P(X>=1)=1-P(X<1)=1-P(X=0)
piii = 1-stats.poisson.pmf(0, 2) ; piii

0.8646647167633873

* A certain store sells seven footballs per day on average.  What is the probability that this store sells four or less footballs in a given day ?

**mean=7 , P(X<=4) = ?**

In [58]:
pcdf = stats.poisson.cdf(4, 7) ; pcdf

0.17299160788207146

In [59]:
# To calculate the mean 
stat.mean(p)

2

In [60]:
# To Calculate the variance 
stat.variance(p)

2

### Geometric Distribution 
*Conditions :*
* i.Repetition of Bernoulli trial unit first success.
* ii.Each trial has a constant probability of success (say p).
* iii.Repeated trials are independent.

We denote the Geometric Distribution as :

$X \sim Geo(p)$

The PMF of Geometric Distribution is written as :
$$F(x)=P(X=x)=p(1-p)^x ,\quad x=0,1,2\cdots \infty$$

It's takes : 
* mean $\mu=\frac{1}{p}$ 
* variance $\sigma^2=\frac{(1-p)}{p^2}$ 
* mgf $M_{x}(t)=\frac{pe^t}{1-(1-p)e^t}$

*Memoryless Property of Geometric Distribution :*

Suppose that an event has not occurred during the first $s$ repetitions. Then probability that it will not occur during the next $t$ repetitions, is the same as the probability that it will not occur during the first $t$ repetition. 
<br> In other words, the information of no success is forgotten so far as subsequent calculations are concerned.

Suppose that *X* has a geometric distribution, then for any two positive integers *s* and *t*, then
<br>$P(X \geq s+t|X>s)=P(X \geq t)$ , coverse is also *TRUE* .

**Note :** *Geometric Distribution is only discrete distribution which has memoryless property.*

In [61]:
# 10 Geometric Random Sample of  prob.=0.6
[p, size] = [0.7, 10]
rgeom = np.random.geometric(p, size) ;rgeom

array([2, 1, 1, 3, 1, 1, 1, 2, 4, 1])

In [62]:
# Generate a random 1x10 distribution for probability 0.6
g = r.geometric(0.6, 10) ;g

array([1, 2, 1, 2, 1, 4, 1, 2, 1, 8])

In [63]:
# Generate random values from Geometric distribution 
# with prob.=0.6 and sample size=10
g1 = stats.geom.rvs(p=0.6, size=10) ;g1

array([1, 1, 2, 5, 3, 1, 3, 1, 2, 2])

In [64]:
# To calculate mean
np.mean(g)

2.3

In [65]:
# Tp calculate variance 
np.var(g)

4.41

**Probability that a missile hits a target is 0.5.
<br> Find out the probability that**
* i) Fourth missile will hit the target.
* ii) Atleast 3 missiles needed to hit the target .
* iii) Atmost 3 missiles required to hit the target.

In [66]:
# i) p=0.5 , P(X=4) ; k=x

gi = stats.geom.pmf(k=4, p=0.5) ; gi

0.0625

In [67]:
# ii) Atleast 3 missiles needed to hit the target . 
# P(X>=3) = 1-P(X<3) = 1-[P(X=0) + P(X=1) + P(X=2)]

gii = 1-sum(stats.geom.pmf([0,1,2], 0.5)) ;gii

0.25

In [68]:
# iii) Atmost 3 missiles required to hit the target.
# P(X<=3) = P(X=0) + P(X=1) + P(X=2) + P(X=3)

giii = sum(stats.geom.pmf([0,1,2,3], 0.5)) ;giii

0.875

In [69]:
# CDF
giv = stats.geom.cdf(3, 0.5) ;giv

0.875

In [70]:
# Percent point function (inverse of cdf — percentiles).
# ppf(q, p, loc=0)

stats.geom.ppf(0.4, 0.6)

1.0

In [71]:
# Mean(‘m’), variance(‘v’), skew(‘s’), 
# and/or kurtosis(‘k’).
# stats(p, loc=0, moments=’mv’)

stats.geom.stats(0.6, moments='mv')

(array(1.66666667), array(1.11111111))

In [72]:
# Median of the distribution
# median(p, loc=0)
stats.geom.median(0.6)

1.0

In [73]:
# Mean of the distribution.
# mean(p, loc=0)
stats.geom.mean(0.6)

1.6666666666666667

In [74]:
# Variance of the distribution.
# var(p, loc=0)
stats.geom.var(0.6)

1.1111111111111114

In [75]:
# Standard deviation of the distribution.
# std(p, loc=0)
stats.geom.std(0.6)

1.0540925533894598

In [76]:
# Moments
stats.geom.moment(0,0.6)

1.0

### Negative-Binomial Distribution
**Conditions :**
* i.Repetition of Bernoulli trial unit $r^{th}$ success.
* ii.Each trial has a constant probability of success (say p).
* iii.Repeated trials are independent.

We denote the pmf of Negative Binomial Distribution as :
<br> $X \sim BIN(r,p)$

Suppose $X=x$, that means at $x^th$ trial there is a success and there are $(r-1)$ successes in $(x-1)$ previous repetitions. If probability of success at each trial is $p$, then probability distribution of $X$ can be written as :
$$P(X=x) = {x+r-1 \choose r-1}p^r(1-p)^x, \quad x=0,1,2,3\cdots \infty$$

Negative Binomial Distribution has :
* mean $\mu=\frac{rq}{p}$ 
* vaiance $\sigma^2=\frac{rq}{p^2}$ 
* mgf $M_x(t)=\frac{p^r}{(1-(1-p)e^t)^r}$

In [77]:
# Generate a random 1x10 distribution for probability 0.6
nb = r.negative_binomial(n=10, p=0.4, size=10) ; nb

array([13, 13, 18, 10, 26, 11, 21,  7, 14, 20])

In [78]:
# Median of the distribution
# median(n,p, loc=0)

stats.nbinom.median(n=10, p=0.4)

14.0

In [79]:
# Mean of the distribution.
# mean(n, p, loc=0)

stats.nbinom.mean(n=10, p=0.4)

15.0

In [80]:
# Variance of the distribution.
# var(n, p, loc=0)

stats.nbinom.var(n=10, p=0.4)

37.5

In [81]:
# Mean(‘m’), variance(‘v’), skew(‘s’), 
# and/or kurtosis(‘k’).
#stats(n, p, loc=0, moments=’mv’)

stats.nbinom.stats(n=10, p=0.4, moments='mv')

(array(15.), array(37.5))

* **Random variates : rvs(n, p, loc=0, size=1)**
* **Probability mass function : pmf(x, n, p, loc=0)**

**Q. An item is produced in large number. The machine is known to produce 5% defective items. A quality control inspector is examining the item by taking at random. What is the probability that atleast 4 items are to be examined in order to get 2 defectives.**

**Ans. :** If 2 defective items to be obtained, then it can be happened in 2 or more trials. The probability of success at each trial is 0.05 . 

In [82]:
# P(X>=4) = 1-P(2<=X<=3)
bin2 = 1-sum(stats.nbinom.pmf([2,3], n=4, p=0.05)) ; bin2

0.999836421875

### Hypergeometric Distribution
We denote Hypergeometric Distribution as;
<br> $X \sim HPG(k; M, N, n)$

Suppose a lot consisting of $N$ items of which $n$ of the items are defective $(N-n)$ of the items are non defective. If a sample of $n \le N$ items are taken randomly without replacement and we define $X$ be the number of defective items in the sample.

We write the PMF of Hypergeometric Distribution as :
$$P(X=x) =\frac{{n \choose k}{N-M \choose n-k}}{{N \choose n}}, k=0,1,2,3,…,min(n,M)$$
where,  $x$ : represents the data set of values, $m$ : size of the population, $n$ : number of samples drawn, $k$ : number of items in the population, $N$ : hypergeometrically distributed values.

It has :
* mean $\mu=\frac{nM}{N}$ 
* vaiance $\sigma^2=\frac{Mn}{N}\frac{(M-1)(n-1)}{(N-1)}$

In [83]:
# Random Simulation 
[M,n,N]=[20,7,12]
rhg = stats.hypergeom.rvs(M, n, N, size=10) ; rhg

array([4, 3, 4, 6, 3, 4, 4, 6, 4, 3])

In [84]:
# Median of the distribution : median(M, n, N, loc=0)
stats.hypergeom.median(M, n, N)

4.0

In [85]:
# Mean of the distribution : mean(M, n, N, loc=0)
stats.hypergeom.mean(M, n, N)

4.199999999999999

In [86]:
# Variance of the distribution : var(M, n, N, loc=0)
stats.hypergeom.var(M, n, N)

1.1494736842105264

In [87]:
# SD of the distribution : std(M, n, N, loc=0)
stats.hypergeom.std(M, n, N)

1.0721351053904198

In [88]:
# Mean(‘m’), variance(‘v’), skew(‘s’), 
# and/or kurtosis(‘k’).
#stats(M,n,N, loc=0, moments=’mv’)

stats.hypergeom.stats(M, n, N, moments='mv')

(array(4.2), array(1.14947368))

In [89]:
# Cumulative distribution function : cdf(k, M, n, N, loc=0)
stats.hypergeom.cdf(4, M, n, N) # k=4

0.6083591331269342

## Continuous Probability Distribution 
### Normal Distribution
Normal(Gaussian / Gauss / Laplace-Gauss) is a type of continuous probability distribution for a real-valued random variable. 
The normal distributions occurs often in nature. 

Normal distributions are important in statistics and are often used in the natural and social sciences to represent real-valued random variables whose distributions are not known.

Normal Distribution is denoted as :
<br> $X \sim N(\mu,\sigma^2)$

It's PDF is denoted as:
$$f_X(x)= \frac{1}{\sigma\sqrt{2\pi}}e^-\frac{(x-\mu)^2}{2\sigma^2}, \quad -\infty<x<+\infty, \quad -\infty<\mu<+\infty, \quad \sigma>0$$
Normal Distribution has :
* mean $\mu$ 
* variance $\sigma^2$ 
* mgf $M_x(t)=e^{\mu t+\frac{1}{2}\sigma^2 t}$

*The Normal pdf is also called as Bell Shape Curve.*

**Properties :**
* i. The curve is bell shaped and symmetric about $\mu$.
* ii. The *mean , median , mode*  of x consider at $\mu$.
* iii. If $X \sim N(\mu,\sigma^2)$ then  $Z=\frac{x-\mu}{\sigma} \tilde \quad N(0,1)$, this vaiate (Z) is *Standard Normal Variate* and it's pdf is $f_{x}(x)\frac{1}{\sqrt{2\pi}}e^-{z^2/2},\quad -\infty<z<+\infty$
* iv. All the odd central moments are zero. i.e. $\mu_{2r+1}=0,\quad r=0,1,2,3,\cdots$ and the even central moments are given by $\mu_{2r=1.3.5......(2r-1)\sigma^{2r}}$
* v. Skewness $\beta_1=0$ and $\gamma_1=\sqrt{\beta_1}=0$
* vi. Kurtosis $\beta_2=3$ and $\gamma_2=\beta_2-3=0$
* vii. Mean Deviation = $\frac{4}{5}\sigma$

    * Quartile Deviation = $\frac{2}{3}\sigma$
    * $QD:MD:SD::10:12:15$
* viii. Area Property :

    * a.$P(\mu-\sigma<X<\mu+\sigma) = 0.6826$
    * b.$P(\mu-2\sigma<X<\mu+2\sigma) = 0.9544$
    * c.$P(\mu-3\sigma<X<\mu+3\sigma) = 0.9973$
* ix. $\Phi_{(-z)} = 1-\Phi_{(z)}$
* x. $P(a \le X \le b) = \Phi(\frac{b-\mu}{\sigma})-\Phi(\frac{a-\mu}{\sigma})$

In [90]:
# 10 Norml Random Sample of mean=3,sd=2
[mean,sd,size] = [3,2,10]
rnorm = np.random.normal(mean, sd, size) ;rnorm

array([ 2.86527657,  1.59177424, -3.4722086 ,  3.86667327,  6.09165961,
        4.02195763,  2.4390429 ,  1.9798123 ,  4.46793209,  1.5162063 ])

In [91]:
# Generate Random Number
n1 = stats.norm.rvs(size=1000) 

In [92]:
# Probability Density Function(PDF)
n2 = stats.norm.pdf(x=3) ; n2 # for x=3

0.0044318484119380075

In [93]:
# Cumulative distribution function(CDF)
n3 = stats.norm.cdf(x=3) ; n3 # for x=3

0.9986501019683699

In [94]:
# Non-central moment of order n
stats.norm.moment(n=1000)

inf

In [95]:
stats.norm.moment(n=100)

2.725392139750729e+78

In [96]:
# Mean(‘m’), variance(‘v’), skew(‘s’)
# and/or kurtosis(‘k’)

stats.norm.stats(2.22, moments='mv') # 2.22 is any random no.

(array(2.22), array(1.))

In [97]:
# Median of the distribution
stats.norm.median(3, 1000)

3.0

In [98]:
# Mean of the distribution
stats.norm.mean(3, 1000)

3.0

In [99]:
# Variance of the distribution
stats.norm.var(3, 1000)

1000000.0

In [100]:
# SD of the distribution
stats.norm.std(3, 1000)

1000.0

### Exponential Distribution
*Poisson process :* A process in which events occur continuously and independently at a constant average rate.

The probability distribution of waiting time between events in a Poisson process is exponential distribution. The exponential distribution can be derived easily from Poisson distribution.

We denote the exponential distribution as :
<br> $X \sim exp(\lambda)$

We denote the PDF of exponential distribution as : 
$$f_{x}(x)= \lambda e^{-\lambda x},\quad x>0,\lambda>0 \Rightarrow F_{x}(x)=1-e^{-\lambda x}$$

Exponential Distribution has 
* $mean = \frac{1}{\lambda}$ 
* $variance = \frac{1}{\lambda^2}$ 
* mgf $M_x(t) = \frac{\lambda}{(\lambda-t)}$

*Memortless Property of Exponential Distribution :*

If $T$ represents the lifetime of a given engine, then probability that engine will work at least $(s+t)$ hrs. given that it has already operated for $s$ hrs. is the same as the initial probability that the engine will function at least $t$ hrs. 
$$P(T>s+t|T>s)=\frac{P(X>s+t)}{P(X>s)}=\frac{e^{-\lambda (s+t)}}{e^{-\lambda s}}$$
which implies $P(T>s+t|t>s)=e^{-\lambda t}=P(T>t)$

**Note :** *Exponential Distribution is only continuous distrgibution which has Memoryless property*

In [101]:
# 10 Exponential Random Sample of mean=3
[mean,size] = [3,10]
rexp = np.random.exponential(mean, size) ;rexp

array([0.69081384, 0.3090427 , 0.95037508, 0.33085762, 1.59653581,
       1.05486993, 7.4593103 , 0.77264828, 8.10084871, 2.27161349])

In [102]:
e1 = stats.expon.rvs(size=1000)

In [103]:
# Probability density function
stats.expon.pdf(x=3) # Pdf for x=3

0.049787068367863944

In [104]:
# Cumulative distribution function
stats.expon.cdf(x=3)

0.950212931632136

In [105]:
# Non-central moment of order n
stats.expon.moment(n=100)

C:\ProgramData\Anaconda3\lib\site-packages\scipy\stats\_distn_infrastructure.py:1790: IntegrationWarning: The algorithm does not converge.  Roundoff error is detected
  in the extrapolation table.  It is assumed that the requested tolerance
  cannot be achieved, and that the returned result (if full_output = 1) is 
  the best which can be obtained.
  return integrate.quad(self._mom_integ1, 0, 1, args=(m,)+args)[0]


1.3861394261902593e+110

In [106]:
e2 = stats.expon.rvs(size=10)
stats.expon.stats(e2, moments='mv')

(array([3.10069471, 3.73620088, 2.36510353, 3.01519899, 1.09429573,
        1.24505219, 3.63460538, 4.68499052, 1.0251258 , 3.46430412]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]))

In [107]:
# Median of the distribution
stats.expon.median(e2)

array([2.79384189, 3.42934806, 2.05825071, 2.70834617, 0.78744291,
       0.93819937, 3.32775256, 4.3781377 , 0.71827298, 3.1574513 ])

In [108]:
# Mean of the distribution
stats.expon.mean(e2)

array([3.10069471, 3.73620088, 2.36510353, 3.01519899, 1.09429573,
       1.24505219, 3.63460538, 4.68499052, 1.0251258 , 3.46430412])

In [109]:
# Variance of the distribution
stats.expon.var(e2)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [110]:
# SD of e1 by numpy
np.std(e1)

0.98232942071236

In [111]:
# Mean of e1 by numpy
np.mean(e1)

0.9771791798004354

### Uniform Distribution
We denote the uniform distribution as :
<br> $X \sim U(a,b)$

We denote the pdf of Uniform Distribution as :
$$f_x(x)=\frac{1}{b-a},\quad a\le x \le b \Rightarrow F_x(x)=\frac{x-a}{b-a},\quad a\le x \le b$$

Uniform Distribution has 
* $mean = \frac{b+a}{2}$ 
* $variance = \frac{(b-a)^2}{12}$ 
* mgf $M_x(t) = \frac{e^{bt}-e^{at}}{(b-a)t}$

In [112]:
# 10 Uniform Random Sample from a=-10 , b=3
[a,b,size] = [-10,3,10]
runif = np.random.uniform(a, b, size) ;runif

array([-6.40407227, -9.07773792,  1.45847963, -0.80919345, -9.61372562,
       -4.22240744,  0.88883501, -7.66706006, -2.30562083, -0.03057034])

In [113]:
# Random Variable between a=3 and b=5
u1 = stats.uniform.rvs(3, 5, size=20) ; u1

array([5.81832125, 6.98328053, 5.89112159, 7.93792979, 3.93598355,
       6.27771983, 4.82614108, 7.89126455, 5.59224537, 4.02718881,
       5.67539821, 5.08547073, 5.06915321, 6.00304536, 4.11411339,
       5.37042835, 4.24703317, 7.22334364, 3.412971  , 6.17896641])

In [114]:
# Mean ny numpy
np.mean(u1)

5.578055991852663

In [115]:
# Variance by numpy
np.var(u1)

1.5806129962984008

In [116]:
# Probability density function
stats.uniform.pdf(10)

0.0

In [117]:
# Cumulative distribution function
stats.uniform.cdf(10)

1.0

In [118]:
# Non-central moment of order n
stats.uniform.moment(n=10)

0.09090909090909093

In [119]:
# Mean(‘m’), variance(‘v’), skew(‘s’)
# and/or kurtosis(‘k’) 
# First Four Moments

stats.uniform.stats(u1, moments='mvsk')

(array([6.31832125, 7.48328053, 6.39112159, 8.43792979, 4.43598355,
        6.77771983, 5.32614108, 8.39126455, 6.09224537, 4.52718881,
        6.17539821, 5.58547073, 5.56915321, 6.50304536, 4.61411339,
        5.87042835, 4.74703317, 7.72334364, 3.912971  , 6.67896641]),
 array([0.08333333, 0.08333333, 0.08333333, 0.08333333, 0.08333333,
        0.08333333, 0.08333333, 0.08333333, 0.08333333, 0.08333333,
        0.08333333, 0.08333333, 0.08333333, 0.08333333, 0.08333333,
        0.08333333, 0.08333333, 0.08333333, 0.08333333, 0.08333333]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.]),
 array([-1.2, -1.2, -1.2, -1.2, -1.2, -1.2, -1.2, -1.2, -1.2, -1.2, -1.2,
        -1.2, -1.2, -1.2, -1.2, -1.2, -1.2, -1.2, -1.2, -1.2]))

### Gamma Distribution
We denote the Gamma Distribution as :
<br> $X \sim \gamma(\alpha,\beta)$

We denote the pdf of Gamma Distribution as : 
$$f_{x}(x;\alpha,\beta)=\frac{1}{\Gamma_{(\alpha)}\beta^{\alpha}}x^{\alpha-1} e^{-x/\beta},\quad \alpha>0,\beta>0,0<x<\infty$$

Gamma Distribution has :
* $mean = \alpha \beta$ 
* $variance = \alpha \beta^2$ 
* mgf $M_x(t) = (\frac{\beta}{(\beta-t)})^{\alpha}$

In [120]:
# 10 Gamma Random Sample of scale 2.33 , shape=0.543
[s,sg,size]=[2.33,0.543,10]
rgamma=np.random.gamma(s,sg,size) ;rgamma

array([0.86968686, 0.72755513, 0.32744213, 0.51298527, 1.80628513,
       0.26916618, 0.41528409, 1.44721757, 0.72332975, 0.52509941])

In [121]:
# Random Simulation 
a = 1.99
g1 = stats.gamma.rvs(a, size=1000)

In [122]:
# PDF for x=3
stats.gamma.pdf(3, a)

0.1483503897331003

In [123]:
# CDF for x=3
stats.gamma.cdf(3, a)

0.80282200386065

In [124]:
# Non-central moment of order n
stats.gamma.moment(10, a)

39117523.35596883

In [125]:
# Mean(‘m’), variance(‘v’), skew(‘s’)
# and/or kurtosis(‘k’)

stats.gamma.stats(a)

(array(1.99), array(1.99))

In [126]:
# Mean of a
np.mean(a)

1.99

In [127]:
# Median of a
np.median(a)

1.99

In [128]:
# Variance of a 
stats.gamma.var(a)

1.99

### Beta Distribution
We denote the Beta Distribution as :
<br> $X \sim \beta(\mu, \nu)$

We denote the PDF of Beta Distribution as :
$$f_{x}(x)=\frac{1}{\beta(\mu,\nu)}x^{\mu-1}(1-x)^{\nu-1}, \quad 0\le x\le 1, \mu>0, \nu>0$$ 
where, $\beta(\mu,\nu)=\frac{\Gamma{\mu}\Gamma{\nu}}{\Gamma{(\mu+\nu)}}$

Beta Distribution has :
* $mean = \frac{\mu}{\mu+\nu}$ 
* $variance = \frac{\mu\nu}{(\mu+\nu)^2(\mu+\nu+1)}$

In [129]:
# 10 Beta Random Sample of sacle(sa)=3.22 , shape(sh)=0.543
[sa,sh,size] = [3.22,0.543,10]
rbeta=np.random.beta(sa, sh, size) ;rbeta

array([0.82359081, 0.95336603, 0.84772317, 0.47204414, 0.99249056,
       0.9892374 , 0.98761979, 0.73801619, 0.9748022 , 0.84721256])

In [130]:
# Random Simulation
[a,b]=[2.31, 0.627]
be1=stats.beta.rvs(a, b, size=10) ;be1

array([0.94341202, 0.76214092, 0.86415896, 0.97770678, 0.67578132,
       0.50764871, 0.9794141 , 0.98110907, 0.92642271, 0.4846018 ])

In [131]:
# Mean by numpy
np.mean(be1)

0.8102396381205027

In [132]:
# Variance by numpy
np.var(be1)

0.03379960905366268

In [133]:
# PDF of Beta Distribution for x=5
stats.beta.pdf(5, a, b)

0.0

In [134]:
# CDF of Beta Beta Distribution for x=5
stats.beta.cdf(5, a, b)

1.0

In [135]:
# first 4 moments
stats.beta.stats(a, b, moments='mvsk')

(array(0.78651685), array(0.04264874), array(-1.12407149), array(0.56545748))

In [136]:
# Median using Scipy
stats.beta.median(a, b)

0.852865976189898

In [137]:
# Mean using Scipy
stats.beta.mean(a, b)

0.7865168539325842

In [138]:
# Variance using Scipy
stats.beta.var(a, b)

0.04264874077027537

In [139]:
# SD using Scipy
stats.beta.std(a, b)

0.20651571555277667

In [140]:
# Mean(‘m’), variance(‘v’), skew(‘s’)
# and/or kurtosis(‘k’)

stats.beta.stats(a, b, moments='mv')

(array(0.78651685), array(0.04264874))

### Log-Normal Distribution
We denote the Log-Normal Distribution as :
<br> $Xlog\sim N(\mu,\sigma^2)$

We denote the PDF of Log-Normal Distribution as :
$$f_x(x)=\frac{1}{\sigma \sqrt{2\pi}}e^{-\frac{(lnx-\mu)^2}{2\sigma^2}}$$

Log-Normal Distribution has 
* $mean = e^{\mu+\sigma^2/2}$ 
* $variance = (e^{\sigma^2}-1)e^{2\mu+\sigma^2}$

In [141]:
# 10 log-Normal Random Sample of mean=3 , sd=2
[ms,vs,size] = [3,2,10]
rlogn = np.random.beta(ms, vs, size) ;rlogn

array([0.11394097, 0.79013872, 0.69374496, 0.43587752, 0.87127621,
       0.66232794, 0.7525598 , 0.54663261, 0.24833714, 0.67031529])

In [142]:
# Random Simulation 
s = 0.954
ln1 = stats.lognorm.rvs(s, size=10) ; ln1

array([0.49036203, 1.74558191, 2.36170603, 1.78476642, 3.26998839,
       0.61784083, 2.40683939, 1.42390597, 2.85237295, 1.89899708])

In [143]:
# Mean by numpy
np.mean(s)

0.954

In [144]:
# Variance by numpy
np.var(s)

0.0

In [145]:
# Median by Scipy
stats.lognorm.median(s)

1.0

In [146]:
# Mean by Scipy
stats.lognorm.mean(s)

1.576264803741382